export const TYPES = {
    READ_STATE: "READ_STATE", // SE AGREGA CON LA BD.JSON DINAMICA
    ADD_TO_CART: "ADD_TO_CART", //AGREGAR UN PRODUCTO AL CARRITO
    REMOVE_ITEM: "REMOVE_ITEM", //REMOVER UNA UNIDAD DE UN PRODUCTO
    REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS", // REMOVER TODAS LAS UNIDADES DE UN PRODUCTO
    CLEAR_CART: "CLEAR_CART", //LIMPIAR TODO EL CARRITO
} 